f = str(input('Digite qualquer coisa: '))
print(f[::2])
t = len(f)
print(t)
z = f.count('i')
print(z)
y = f.find('qu')
print(y)
d = 'gta' in f
print(d)
o = f.replace('qualquer', 'alguma')
print(o)
m = f.upper()
k = m.replace('qualquer', 'alguma')
print(k)
l = m.lower()
print(l)
m2 = m.capitalize()
print(m2)
g = f.title()
print(g)
p = f.strip()
h = f.rstrip()
s = f.lstrip()
c = f.split()
r = '-'.join(m)
print(r)


