print('o titulo do codee aqui e ola mundo entao tem e ter pelo menos um ola mundo hahaahah')
print('fala mano blz suave')
n1 = input('man digita um numero: ')
n2 = input('agora ovem digite m outro numero: ')
print('valores abaixo kkk')
print('a soma de' ,n1 ,'e' ,n2,'e igual a',int(n1)+int(n2),'correto')
print('e nois me pexe hahaha')
